### PR TITLE
Enhancement/attach tooltips/#60

### PR DESCRIPTION
**Pull request by alexkirsz**
#60

### CODE REVIEW

**Comment by zallek** [comment]
Should Append and Tooltip^remain in tooltip folder ?

**Comment by alexkirsz** [comment]
No, maybe create a misc/others folder or just move them up a folder. Still need a better and more descriptive name for `Tooltip`. Maybe `Positioned`? Also, HoverTooltip show be renamed to `FollowCursor`.

**Comment by zallek** [comment]
- In a folder Misc or Helpers ?
- Positioned, don't have any better ideas :p
- FollowCursor :+1:

**Comment by zallek** [comment]
:+1:

**Pull request merged**
