### PR TITLE
feature/horizontalgauge-format-tooltip/#45

### PR DESCRIPTION
**Pull request by alexkirsz**
I hesitated between passing a function that returns a node (formatValue => ReactNode) and directly passing a node. A node is any object React can render (ReactElement/String/Array<ReactElement>/etc.).

I went with passing a node as the `display` property on stacks props. @zallek thoughts?

### CODE REVIEW

**Comment by zallek** [comment]
@Morhaus why not adding the logic to compute percentages in the component ? As it's something will want to reuse often ?

**Comment by alexkirsz** [comment]
@zallek I'd rather have the application decide on the formatting. For instance, we might want to append a suffix to the value, or customize the formatting of the number depending on the locale (`6,900` vs `6.900`).

**Comment by alexkirsz** [comment]
Looking back, I actually prefer defining a single `formatValue` prop method on the `HorizontalGauge` component to mirror the way `VennDiagram` works.

**Comment by alexkirsz** [comment]
The only issue with that is that we need to distinguish the `all` value from the other stacks `value` as we don't want to format it the same way.

**Comment by zallek** [comment]
:+1:

**Pull request merged**
