### PR TITLE
Task/update eslint and rules

### PR DESCRIPTION
**Pull request by zallek**
#56

Eslint version 0.21.0
- Stylistic rules aren't Exhaustive

### CODE REVIEW

**Comment by zallek** [comment]
`var` used not like `let` variables according to EsLint
image

In both `example` and `src` `Search Select`, it was nested destrucuring, so it's OK
image

And in `utils` it shoudln't be a problem either
image

**Comment by zallek** [comment]
retest this please

**Comment by alexkirsz** [comment]
@zallek you need to go to the build page and click the refresh button to restart a build. I've restarted it.

**Comment by Morhaus** [comment]
:+1:

**Pull request merged**
