### PR TITLE
Bug/searchselect/#58

### PR DESCRIPTION
**Pull request by alexkirsz**
#58

### CODE REVIEW

**Comment by alexkirsz** [comment]
Does not fix `Selecting the input does not show the caret but the input is still editable`.

**Comment by alexkirsz** [comment]
@zallek does my solution for cancelling blur work for you? there might be regressions

**Comment by alexkirsz** [comment]
TODO: Add `disabled` prop/behavior to SearchSelect.

**Comment by zallek** [comment]
Could you test on IE, Firefox, Safari, Chrome pls ?
Otherwise :+1:

**Pull request merged**
