### PR TITLE
Enhancement/remove bootstrap/#51

### PR DESCRIPTION
**Pull request by alexkirsz**
#51

### CODE REVIEW

**Comment by zallek** [comment]
`"bootstrap-sass": "~3.3.3"` is still in the dependecies
As for `"font-awesome": "~4.1.0"`

Plus we have both `"bootstrap": "^3.3.2",` and `"bootstrap-sass": "~3.3.3"`

**Comment by alexkirsz** [comment]
We're still using font-awesome in some examples so I'll move it to devDependencies.
Same for bootstrap (used in index.html).

On the other hand, we're not using `bootstrap-sass` at all anymore so I'll remove it completely.

**Comment by zallek** [comment]
nice.

**Comment by zallek** [comment]
:+1:

**Pull request merged**
