### PR TITLE
task/travis/#33

### PR DESCRIPTION
**Pull request by alexkirsz**
#33

### CODE REVIEW

**Comment by zallek** [comment]
As on the report, repo should have atomic scripts
- Bootstrap app
- build app (without installing)
- launch tests (without checking syntext)
- launch checking syntax

so we talked about with @jbbarth `.travis.yml` should be like:

``` YML
...
before_script:
  - ./script/bootstrap
script:
  - ./script/build
  - ./script/test
  - ./script/check
```

**Comment by jbbarth** [comment]
I think "script/check" should be ran before "script/test" (it's usually quicker and that way you'll catch syntax/linting problems before running the test suite, no?)

Also I don't know if the "script/build" script should preferably go in "before_script" or "script" section, but both should be ok.

Last thing, beware it's "bootstrap" not "boostrap"

**Comment by zallek** [comment]
Actually when you read the documentation it's seems to be more like:
http://docs.travis-ci.com/user/build-configuration/

``` YML
install:
  - ./script/bootstrap
script:
  - ./script/build
  - ./script/check
  - ./script/test
```

and keep `build` in `script` because it can fail for somewhat reason.

Note: it's important to use scripts on CI environnements, so that, scripts are also tested :)

**Comment by jbbarth** [comment]
Perfect :+1:

**Comment by alexkirsz** [comment]
Adding scripts wasn't in the scope of this PR/issue. I'm doing that next for https://github.com/botify-labs/react-components/issues/28. Can I merge this?

**Comment by zallek** [comment]
You can add scripts in this should as it should change things in your gulp/webpack config.
https://github.com/botify-labs/react-components/pull/34#issuecomment-88104388
https://github.com/botify-labs/react-components/pull/34#issuecomment-88110974

**Comment by alexkirsz** [comment]
Btw, I agree with @jbbarth that linting should happen before building the library as it will always be quicker and might break more often. But from my tests it looked like travis kept running commands even though an anterior one had failed, so it might not change anything.

**Comment by jbbarth** [comment]
> and might break more often.

Except if you leave it in a pre-commit hook ;) No more problem then

**Comment by alexkirsz** [comment]
We have linting integrated to Sublime and continuously running in the dev process. This requires preliminary setup, but I think pre-commit hooks do too?

**Comment by alexkirsz** [comment]
@jbbarth @zallek https://travis-ci.org/botify-labs/react-components/builds/56694917 http://stackoverflow.com/posts/26342292/revisions wat do

Edit: nvm, adding `sudo: required` to travis.yml kinda worked

**Comment by alexkirsz** [comment]
@jbbarth Need help, Travis can't find nodejs@0.10.25\* (`E: Version '0.10.25*' for 'nodejs' was not found`)

Should I add a custom PPA?

**Comment by alexkirsz** [comment]
YES

**Comment by alexkirsz** [comment]
It's (almost) done T-T

**Pull request merged**
